# Generated by Django 4.1 on 2022-09-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField(max_length=250)),
                ('product_price', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=30)),
                ('specification', models.CharField(max_length=40)),
                ('pic', models.FileField(default='media/product_default.png', upload_to='media/images/')),
                ('shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopkeeper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
