# Generated by Django 4.1 on 2022-09-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_size', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='specification',
        ),
        migrations.AddField(
            model_name='products',
            name='s_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ramspecification'),
        ),
    ]
