# Generated by Django 4.1 on 2022-09-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ramspecification_remove_products_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(default='media/product_default.png', upload_to='media/images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopkeeper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
