# Generated by Django 4.1 on 2022-09-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_qty', models.CharField(max_length=30)),
                ('total_price', models.CharField(max_length=30)),
                ('status', models.CharField(default='Order Raise', max_length=80)),
                ('order_accept_status', models.CharField(default='PENDING', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('order_net_amount', models.CharField(default='', max_length=30)),
                ('Shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopkeeper')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
